# Generated by Django 5.2.4 on 2025-12-08 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0002_learningsession_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningsession',
            name='scheduled_time',
        ),
        migrations.AddField(
            model_name='learningsession',
            name='review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_review', to='swap.review'),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='learningsession',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='learningsession',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='learningsession',
            name='status',
            field=models.CharField(default='Ongoing', max_length=20),
        ),
        migrations.AlterField(
            model_name='learningsession',
            name='topic',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='feedback',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='swap.learningsession'),
        ),
    ]
