# Generated by Django 5.2.4 on 2025-12-09 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0004_remove_review_session_alter_learningsession_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='swap.learningsession'),
        ),
        migrations.AlterField(
            model_name='learningsession',
            name='review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_link', to='swap.review'),
        ),
    ]
