# Generated by Django 5.2.4 on 2025-12-09 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0005_review_session_alter_learningsession_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='session',
        ),
        migrations.AlterField(
            model_name='learningsession',
            name='review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_review', to='swap.review'),
        ),
    ]
