# Generated by Django 5.2.4 on 2025-12-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0008_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
