# Generated by Django 6.0 on 2026-07-02 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_delivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='delivered',
        ),
    ]
